#!/bin/bash

# Git PAT Terminal Form
# A terminal-based form for Git operations using Personal Access Token (PAT)
# Author: @Salty1960

set -e

# Colors for better terminal output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# Configuration file
CONFIG_FILE="$HOME/.git-pat-config"

# Function to print colored output
print_color() {
    local color=$1
    local message=$2
    echo -e "${color}${message}${NC}"
}

# Function to print header
print_header() {
    clear
    print_color $CYAN "=================================="
    print_color $CYAN "   Git PAT Terminal Form"
    print_color $CYAN "=================================="
    echo
}

# Function to read input with prompt
read_input() {
    local prompt=$1
    local var_name=$2
    local default_value=$3
    local hide_input=$4
    
    if [ -n "$default_value" ]; then
        prompt="$prompt [$default_value]"
    fi
    
    print_color $YELLOW "$prompt: "
    
    if [ "$hide_input" = "true" ]; then
        read -s input_value
        echo
    else
        read input_value
    fi
    
    if [ -z "$input_value" ] && [ -n "$default_value" ]; then
        input_value="$default_value"
    fi
    
    eval "$var_name='$input_value'"
}

# Function to save configuration
save_config() {
    local username=$1
    local repo_url=$2
    
    cat > "$CONFIG_FILE" << EOF
# Git PAT Configuration
# Generated by git-pat-terminal.sh
USERNAME="$username"
REPO_URL="$repo_url"
EOF
    
    chmod 600 "$CONFIG_FILE"
    print_color $GREEN "Configuration saved to $CONFIG_FILE"
}

# Function to load configuration
load_config() {
    if [ -f "$CONFIG_FILE" ]; then
        source "$CONFIG_FILE"
        return 0
    else
        return 1
    fi
}

# Function to validate PAT
validate_pat() {
    local pat=$1
    local username=$2
    
    print_color $BLUE "Validating PAT..."
    
    # Test PAT by making a simple API call
    response=$(curl -s -H "Authorization: token $pat" \
                   -H "Accept: application/vnd.github.v3+json" \
                   "https://api.github.com/user" 2>/dev/null || echo "ERROR")
    
    if echo "$response" | grep -q "login"; then
        print_color $GREEN "✓ PAT validation successful"
        return 0
    else
        print_color $RED "✗ PAT validation failed"
        return 1
    fi
}

# Function to setup git credentials
setup_git_credentials() {
    local username=$1
    local pat=$2
    
    print_color $BLUE "Setting up Git credentials..."
    
    # Configure git to use the PAT
    git config --global credential.helper store
    git config --global user.name "$username"
    
    # Create credentials file entry
    echo "https://$username:$pat@github.com" > ~/.git-credentials
    chmod 600 ~/.git-credentials
    
    print_color $GREEN "✓ Git credentials configured"
}

# Function to perform git pull
perform_git_pull() {
    local repo_url=$1
    local branch=$2
    
    print_color $BLUE "Performing git pull..."
    
    if [ ! -d ".git" ]; then
        print_color $YELLOW "Not in a git repository. Cloning repository..."
        git clone "$repo_url" .
    else
        print_color $BLUE "Pulling from $branch branch..."
        git pull origin "$branch"
    fi
    
    print_color $GREEN "✓ Git pull completed successfully"
}

# Main menu function
show_menu() {
    echo
    print_color $CYAN "Available Operations:"
    echo "1. Configure PAT and Repository"
    echo "2. Pull Repository"
    echo "3. View Current Configuration"
    echo "4. Test PAT"
    echo "5. Exit"
    echo
    read_input "Select an option (1-5)" choice ""
}

# Function to configure PAT and repository
configure_pat() {
    print_header
    print_color $YELLOW "=== PAT Configuration ==="
    echo
    
    # Load existing config if available
    load_config || true
    
    read_input "GitHub Username" username "$USERNAME"
    read_input "Personal Access Token" pat "" "true"
    read_input "Repository URL (https://github.com/user/repo.git)" repo_url "$REPO_URL"
    
    # Validate PAT
    if validate_pat "$pat" "$username"; then
        setup_git_credentials "$username" "$pat"
        save_config "$username" "$repo_url"
        print_color $GREEN "Configuration completed successfully!"
    else
        print_color $RED "Configuration failed due to invalid PAT"
        return 1
    fi
}

# Function to pull repository
pull_repository() {
    print_header
    print_color $YELLOW "=== Repository Pull ==="
    echo
    
    if ! load_config; then
        print_color $RED "No configuration found. Please configure PAT first."
        return 1
    fi
    
    read_input "Branch to pull" branch "main"
    read_input "Target directory" target_dir "$(pwd)"
    
    cd "$target_dir"
    perform_git_pull "$REPO_URL" "$branch"
}

# Function to view current configuration
view_config() {
    print_header
    print_color $YELLOW "=== Current Configuration ==="
    echo
    
    if load_config; then
        print_color $GREEN "Username: $USERNAME"
        print_color $GREEN "Repository URL: $REPO_URL"
        print_color $GREEN "Config file: $CONFIG_FILE"
    else
        print_color $RED "No configuration found"
    fi
    
    echo
    read -p "Press Enter to continue..."
}

# Function to test PAT
test_pat() {
    print_header
    print_color $YELLOW "=== PAT Test ==="
    echo
    
    if ! load_config; then
        print_color $RED "No configuration found. Please configure PAT first."
        return 1
    fi
    
    read_input "Personal Access Token to test" pat "" "true"
    validate_pat "$pat" "$USERNAME"
    
    echo
    read -p "Press Enter to continue..."
}

# Main execution
main() {
    while true; do
        print_header
        show_menu
        
        case $choice in
            1)
                configure_pat
                ;;
            2)
                pull_repository
                ;;
            3)
                view_config
                ;;
            4)
                test_pat
                ;;
            5)
                print_color $GREEN "Goodbye!"
                exit 0
                ;;
            *)
                print_color $RED "Invalid option. Please try again."
                sleep 2
                ;;
        esac
        
        echo
        read -p "Press Enter to continue..."
    done
}

# Check if script is being run directly
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi